version: '3'
services:
  backend:
    container_name: app_backend
    build: ./
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=jwt_secret
      - DIALECT=postgres
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    volumes:
      - ./:/app-backend
  db:
    image: postgres
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: 'always'
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE